version: "3.8"

networks:
  dev-cloud-network:

services:
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./src/nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #TODO: agregar servicios de los que depende

  backend:
    build:
      context: ./src/backend  # Ruta donde se encuentra el Dockerfile
      dockerfile: Dockerfile  # Nombre del Dockerfile
    ports:
      - "8000:8000"
    networks:
      - dev-cloud-network
  # broker:
  #TODO: agregar servicio de broker
  # database:
  #TODO: agregar servicio de base de datos
  # worker:
  #TODO: agregar servicio de worker