version: "3.8"

services:
  backend-api:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      AMQP_URL: 'amqp://broker_video?connection_attempts=10&retry_delay=10'
    volumes:
      - videos_sin_editar:/usr/src/app/uploads/videos_sin_editar
      - videos_editados:/usr/src/app/uploads/videos_editados

volumes:
  videos_sin_editar:
  videos_editados: